### ISSUE TITLE
PVVX format and receiving address issue

### ISSUE THREAD

**Issue by Hendrick42** [diyless/ble-repeater#1]
Hi, thanks for your work.
I got your code working, but had to remove the "AdFlags" with the PVVX format - otherwise its lenght is 22 not 19.
The device (ESPC3) is receiving and advertising the one thermometer.

Right now I am receiving the data with [https://github.com/matthias-bs/ATC_MiThermometer](https://github.com/matthias-bs/ATC_MiThermometer) on a ESP32 which is working without the proxy - but the "proxied" data is not received.

Does the receiver software have to "know" that is has been proxied or should it work transparently?

**Comment by Hendrick42** [comment]
Interesting - just found out that there is a address missmatch. 
The device has the ED:30:31 mac - if I enable the proxy if both are ca. the same distance - there is a new mac the "32" which has the same values as the :31 device... If I unplug the proxy, the :32 is disappearing...

3:35:46.928 -> Sensor 0: A4:C1:38:ED:30:31
23:35:46.928 -> 22.52°C
23:35:46.928 -> 53.96%
23:35:46.928 -> 2.992V
23:35:46.928 -> 88%
23:35:46.928 -> -82dBm

23:35:46.960 -> 
23:35:46.960 -> Sensor 1: A4:C1:38:ED:30:32
23:35:46.960 -> 22.52°C
23:35:46.960 -> 53.96%
23:35:46.960 -> 2.992V
23:35:46.960 -> 88%
23:35:46.960 -> -80dBm

also happes to be the case with 4 other addresses - always address +1

**Comment by tshcherban** [comment]
It should work transparently, ill try investigating the case with an altered original address

**Comment by diyless** [comment]
Hi @Hendrick42 we've [fixed ](https://github.com/diyless/ble-repeater/commit/594164e29d9986a1979055f5db371b9561541cd4) a repeated BLE address issue on an ESP32-C3 board. Can you give a try?

**Comment by Hendrick42** [comment]
I just also did a test - shifting -2 - instead -1 - on the old code did work. Will give your commit a try

**Comment by Hendrick42** [comment]
> Hi @Hendrick42 we've [fixed ](https://github.com/diyless/ble-repeater/commit/594164e29d9986a1979055f5db371b9561541cd4) a repeated BLE address issue on an ESP32-C3 board. Can you give a try?

your commit is working on the ESP32C3, thanks!
